version: 1
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install 

      # run test
      - run: npm run test

      # run build 
      - run: npm run build